name: Update Council HTMLs

on:
  schedule:
    - cron: '0 0 * * *'   # 9:00 JST
    - cron: '0 4 * * *'   # 13:00 JST
    - cron: '0 9 * * *'   # 18:00 JST
  workflow_dispatch:      # 手動実行ボタン

# Node.js 24への対応を強制する設定を追加
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # v3 から v4 へ

      - name: Set up Python
        uses: actions/setup-python@v5 # v4 から v5 へ
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install beautifulsoup4 selenium webdriver-manager lxml

      - name: Run Scrapers
        run: |
          cd src
          python 200_METI審議会.py
          python 201_METI審議会（エネ庁）.py
          python 300_監視等委審議会.py
          python 400_内閣府審議会.py

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Auto-update HTMLs: $(date)" || exit 0
          git push